# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Desktop\HotelManagementSystem\src\main\resources\base\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.newRes = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Res/48px-Appointment-new.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newRes.setIcon(icon)
        self.newRes.setObjectName("newRes")
        self.newRoom = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rm/48px-Go-home-2.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newRoom.setIcon(icon1)
        self.newRoom.setObjectName("newRoom")
        self.newService = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/srv/48px-Edit-clear.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newService.setIcon(icon2)
        self.newService.setObjectName("newService")
        self.newCustomer = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ctmr/48px-System-users-3.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newCustomer.setIcon(icon3)
        self.newCustomer.setObjectName("newCustomer")
        self.cancelRes = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Res/48px-System-log-out.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelRes.setIcon(icon4)
        self.cancelRes.setObjectName("cancelRes")
        self.toolBar.addAction(self.newRes)
        self.toolBar.addAction(self.cancelRes)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.newRoom)
        self.toolBar.addAction(self.newCustomer)
        self.toolBar.addAction(self.newService)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chart of Customers by Age"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Chart of Earnings by Month"))
        self.groupBox.setTitle(_translate("MainWindow", "All Current Reservations"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.newRes.setText(_translate("MainWindow", "newRes"))
        self.newRes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create, edit, or delete a Reservation</p></body></html>"))
        self.newRes.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.newRoom.setText(_translate("MainWindow", "newRoom"))
        self.newRoom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create, edit, or delete a Room</p></body></html>"))
        self.newRoom.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.newService.setText(_translate("MainWindow", "newService"))
        self.newService.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create, edit, or delete a Service</p></body></html>"))
        self.newService.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.newCustomer.setText(_translate("MainWindow", "newCustomer"))
        self.newCustomer.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create, edit, or delete a Customer</p></body></html>"))
        self.newCustomer.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.cancelRes.setText(_translate("MainWindow", "cancelRes"))
        self.cancelRes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cancel a current Reservation</p></body></html>"))
        self.cancelRes.setShortcut(_translate("MainWindow", "Ctrl+Shift+M"))

import rc_rc
