# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Desktop\HotelManagementSystem\src\main\resources\base\room.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Room(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 377)
        """self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")"""
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setObjectName("tableView")
        self.tableView.setEditTriggers(self.tableView.NoEditTriggers)
        self.gridLayout_4.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_4)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.setEditTriggers(self.tableView_2.NoEditTriggers)
        self.gridLayout_5.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 7, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Reservation History"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Current Reservations"))
        self.groupBox.setTitle(_translate("MainWindow", "Information"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Commands"))
        self.pushButton_3.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "Room Number:"))
        self.spinBox.setPrefix(_translate("MainWindow", "$"))
        self.label_3.setText(_translate("MainWindow", "Date of Birth:"))
        self.label_2.setText(_translate("MainWindow", "Price"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Single"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Double"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Triple"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Quad"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Queen"))
        self.comboBox.setItemText(5, _translate("MainWindow", "King"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Twin"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Hollywood Twin"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Double-Double"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Studio"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Suite / Executive Suite"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Mini Suite / Junior Suite"))
        self.comboBox.setItemText(12, _translate("MainWindow", "President Suite / Presidential Suite"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Apartment"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Connecting Rooms"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Murphy Room"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Accessible Room / Disabled Room"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Cabana"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Villa"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Executive Floor / Floored Room"))
        self.comboBox.setItemText(20, _translate("MainWindow", "Non-Smoking Room"))
        self.comboBox.setItemText(21, _translate("MainWindow", "Smoking Room"))

